/**
 * ==========================================
 * ROYAL - CRYPTO CHECKOUT (V4.0)
 * ==========================================
 * Standard checkout only:
 * - No promos
 * - No referral bonuses
 * - Value model: 1 CROWN = 1 USD
 * - For deposits: 1 USDT = 1 USD
 */

(function () {
  function role(stateObj) {
    return String(stateObj.role || stateObj.activeRole || 'guest').toLowerCase();
  }

  function getStore() {
    return window.ROYAL_STORE;
  }

  function fmt(n, d = 2) {
    const x = Number(n || 0);
    if (!Number.isFinite(x)) return '0';
    if (window.formatNumber) return window.formatNumber(x, { minimumFractionDigits: d, maximumFractionDigits: d });
    return x.toLocaleString(undefined, { minimumFractionDigits: d, maximumFractionDigits: d });
  }

  function escapeHtml(s) {
    return String(s || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  function defaultAddressFor(network) {
  const n = String(network || 'TRC20').toUpperCase();
  // In production this address must be generated by the backend gateway per invoice.
  if (n === 'ERC20') return '0x… (generated by gateway)';
  return 'T… (generated by gateway)';
}

  function computeOffer({ usdtAmount, cfg, network }) {
    const usdt = Math.max(0, Number(usdtAmount || 0));
    const crownUsdRate = 1; // fixed
    const usd = usdt; // 1 USDT = 1 USD
    const n = String(network || 'TRC20').toUpperCase();
    const feeMap = (cfg && cfg.networkFeesUSDT) ? cfg.networkFeesUSDT : { TRC20: 1, ERC20: 3 };
    const networkFee = Math.max(0, Number(feeMap[n] ?? (n==='ERC20'?3:1)));
    const netUSDT = Math.max(0, usdt - networkFee);
    const netUSD = netUSDT;
    const crowns = netUSD / crownUsdRate;
    return {
      usdt,
      networkFee,
      netUSDT,
      usd: netUSD,
      crowns,
      crownUsdRate,
    };
  }

  window.renderCryptoCheckout = function (stateObj) {
    const t = window.t || ((k)=>k);
    const r = role(stateObj);
    const store = getStore();

    if (r === 'guest') {
      return `
        <div class="poker-auth-card p-10 rounded-3xl max-w-2xl mx-auto border border-rcRed/30 text-center">
          <div class="text-5xl mb-6">🔒</div>
          <div class="text-white font-black text-2xl uppercase tracking-widest">${t('checkout.lockedTitle')}</div>
          <div class="text-rcSlateLight text-sm mt-3">${t('checkout.lockedBody')}</div>
          <button onclick="window.navigateTo('auth_register')" class="mt-8 poker-chip-btn px-10 py-4 rounded-xl text-rcNavyBase font-black uppercase text-[10px] tracking-widest">${t('lobby.register')}</button>
        </div>
      `;
    }

    const cfg = store.loadConfig();

    stateObj.ui = stateObj.ui || {};
    if (!Number.isFinite(Number(stateObj.ui.buyAmount))) stateObj.ui.buyAmount = 1000;
    if (!stateObj.ui.buyNetwork) stateObj.ui.buyNetwork = 'TRC20';

    const offer = computeOffer({ usdtAmount: stateObj.ui.buyAmount, cfg, network: stateObj.ui.buyNetwork });
    const pendingTable = stateObj.ui.pendingJoinTableId;

    const invoiceId = stateObj.ui.activeInvoiceId;
    const invoice = invoiceId ? (store.loadDeposits().find(x => x.id === invoiceId) || null) : null;

    return `
      <div class="max-w-6xl mx-auto fade-in">
        <div class="flex flex-col lg:flex-row gap-8">
          <div class="flex-1">
            <div class="bg-rcNavyPanel border border-rcNavyBorder rounded-3xl p-8 shadow-inner">
              <div class="flex items-start justify-between gap-6">
                <div>
                  <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('checkout.buyCrown')}</div>
                  <div class="text-white font-black text-3xl mt-2">${t('checkout.cryptoCheckout')}</div>
                  <div class="text-rcSlateLight text-sm mt-2">${t('checkout.standardOnly')}</div>
                </div>
                <div class="bg-black/30 border border-rcGold/20 rounded-2xl px-4 py-3 text-right">
                  <div class="text-[9px] text-rcSlate uppercase tracking-widest font-bold">${t('checkout.valueModel')}</div>
                  <div class="text-rcGold font-mono font-black text-xl">1 CROWN = $1.00</div>
                  <div class="text-rcSlateLight text-[10px] mt-1">1 USDT = 1 USD</div>
                </div>
              </div>

              <div class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="md:col-span-2">
                  <label class="text-[9px] text-rcSlate uppercase tracking-widest font-bold">${t('checkout.amountUSDT')}</label>
                  <input id="buy_amount" type="number" value="${escapeHtml(stateObj.ui.buyAmount)}" min="0" class="mt-2 w-full poker-input p-3 rounded-xl text-sm" oninput="window.setBuyAmount(this.value)">
                </div>
                <div>
                  <label class="text-[9px] text-rcSlate uppercase tracking-widest font-bold">${t('checkout.network')}</label>
                  <select onchange="window.setBuyNetwork(this.value)" class="mt-2 w-full bg-rcNavyBase border border-rcNavyBorder text-white p-3 rounded-xl text-sm">
                    ${['TRC20','ERC20'].map(n => `<option value="${n}" ${stateObj.ui.buyNetwork===n?'selected':''}>${n}</option>`).join('')}
                  </select>
                  <div class="mt-2 text-[11px] text-rcSlateLight">
                    ⚠️ ${t('checkout.networksWarning',{TRC20:(window.wrapLTR?window.wrapLTR('TRC20'):'TRC20'), ERC20:(window.wrapLTR?window.wrapLTR('ERC20'):'ERC20')})}
                  </div>
                </div>
              </div>

              <div class="mt-8 bg-rcNavyBase/50 border border-rcNavyBorder rounded-2xl p-6">
                <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('checkout.calculation')}</div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 text-sm">
                  <div class="bg-black/20 border border-rcNavyBorder rounded-xl p-4">
                    <div class="text-rcSlateLight text-xs">${t('checkout.youReceive')}</div>
                    <div class="text-rcGold font-mono font-black text-3xl">${fmt(offer.crowns, 2)} CROWN</div>
                    <div class="text-rcSlateLight text-xs mt-3">${t('checkout.breakdown')}</div>
                    <div class="mt-2 space-y-1 text-sm">
                      <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.gross')}</span><span class="text-white font-mono font-bold">${fmt(offer.usdt,2)} USDT</span></div>
                      <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.networkFee')}</span><span class="text-rcRed font-mono font-bold">-${fmt(offer.networkFee,2)} USDT</span></div>
                      <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.netCredited')}</span><span class="text-rcGold font-mono font-black">${fmt(offer.netUSDT,2)} USDT</span></div>
                    </div>
                  </div>
                  <div class="bg-black/20 border border-rcNavyBorder rounded-xl p-4">
                    <div class="text-rcSlateLight text-xs">${t('checkout.notes')}</div>
                    <div class="text-white text-sm mt-2">${t('checkout.notesBody')}</div>
                    <div class="text-rcSlateLight text-xs mt-3">${t('checkout.addressShown')}</div>
                  </div>
                </div>
              </div>

              <div class="mt-6 flex gap-3">
                <button onclick="window.createStandardInvoice()" class="flex-1 poker-chip-btn py-4 rounded-2xl text-rcNavyBase font-black uppercase tracking-widest text-[10px]">${t('checkout.createInvoice')}</button>
                <button onclick="window.navigateTo('smart_lobby')" class="px-6 py-4 rounded-2xl bg-rcNavyPanel border border-rcNavyBorder text-rcSlateLight hover:text-white font-bold uppercase text-[10px] tracking-widest">${t('common.back')}</button>
              </div>

              ${pendingTable ? `<div class="mt-4 text-rcSlateLight text-xs">${t('checkout.pendingJoin')} <span class="text-white font-mono">${escapeHtml(pendingTable)}</span></div>` : ''}
            </div>
          </div>

          <div class="w-full lg:w-[420px]">
            ${renderInvoicePanel(invoice, stateObj)}
          </div>
        </div>
      </div>
    `;
  };

  function renderInvoicePanel(invoice, stateObj) {
    const t = window.t || ((k)=>k);
    const store = getStore();
    if (!invoice) {
      return `
        <div class="bg-rcNavyPanel border border-rcNavyBorder rounded-3xl p-8 shadow-inner">
          <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('checkout.invoice')}</div>
          <div class="text-white font-black text-xl mt-2">${t('checkout.noInvoice')}</div>
          <div class="text-rcSlateLight text-sm mt-3">${t('checkout.createInvoiceTip')}</div>
          <div class="mt-6 bg-black/20 border border-rcNavyBorder rounded-2xl p-5">
            <div class="text-rcSlateLight text-xs">${t('checkout.tip')}</div>
            <div class="text-white text-sm mt-1">${t('checkout.trcCheaper',{TRC20:(window.wrapLTR?window.wrapLTR('TRC20'):'TRC20')})}</div>
          </div>
        </div>
      `;
    }

    const statusColor = invoice.status === 'finished' ? 'text-rcGreen' : (invoice.status === 'confirming' ? 'text-rcGold' : 'text-rcSlateLight');
    const pct = Math.round((invoice.confirmations / invoice.requiredConfirmations) * 100);

    return `
      <div class="bg-rcNavyPanel border border-rcNavyBorder rounded-3xl p-8 shadow-inner">
        <div class="flex items-start justify-between">
          <div>
            <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('checkout.invoice')}</div>
            <div class="text-white font-black text-xl mt-2">${window.wrapLTR ? window.wrapLTR(invoice.id) : escapeHtml(invoice.id)}</div>
            <div class="text-[10px] mt-2 ${statusColor} font-black uppercase tracking-widest">${t('checkout.statusLabel')}: ${escapeHtml((window.t?window.t('checkout.status_'+invoice.status):invoice.status) || invoice.status)}</div>
          </div>
          <button onclick="window.clearInvoice()" class="text-rcSlate hover:text-white">✕</button>
        </div>

        <div class="mt-6 bg-black/20 border border-rcNavyBorder rounded-2xl p-5">
          <div class="text-rcSlateLight text-xs">${t('checkout.sendExactly')}</div>
          <div class="text-white font-mono font-black text-2xl mt-1">${fmt(invoice.usdtToSend, 2)} USDT</div>
          <div class="text-rcSlateLight text-xs mt-4">${t('checkout.network')}</div>
          <div class="text-white font-mono font-bold">${escapeHtml(invoice.network)}</div>
          <div class="text-rcSlateLight text-xs mt-4">${t('checkout.address')}</div>
          <div class="text-white font-mono text-xs break-all">${window.wrapLTR ? window.wrapLTR(invoice.address) : escapeHtml(invoice.address)}</div>
        </div>

        <div class="mt-6">
          <div class="flex justify-between text-[10px] text-rcSlateLight uppercase tracking-widest font-bold">
            <span>${t('checkout.confirmations')}</span>
            <span>${invoice.confirmations}/${invoice.requiredConfirmations}</span>
          </div>
          <div class="w-full bg-rcNavyBase rounded-full h-2 mt-2 border border-rcNavyBorder overflow-hidden">
            <div class="bg-rcGold h-2 rounded-full" style="width:${pct}%;"></div>
          </div>
        </div>

        ${invoice.status !== 'finished' ? `
          <button onclick="window.simulateConfirmations()" class="mt-6 w-full poker-chip-btn py-3 rounded-2xl text-rcNavyBase font-black uppercase tracking-widest text-[10px]">${t('checkout.simulateTick')}</button>
        ` : `
          <div class="mt-6 bg-rcGreen/10 border border-rcGreen/30 p-5 rounded-2xl">
            <div class="text-rcGreen font-black uppercase tracking-widest text-[10px]">${t('checkout.credited')}</div>
            <div class="text-white text-sm mt-2">${t('checkout.addedToWallet',{amount: fmt(invoice.crownsToCredit, 2)})}</div>
            <div class="text-rcSlateLight text-xs mt-2">${t('checkout.txid')}: <span class="text-white font-mono">${window.wrapLTR ? window.wrapLTR(invoice.txid || '') : escapeHtml(invoice.txid || '')}</span></div>
            <button onclick="window.postDepositNextStep()" class="mt-5 w-full bg-rcNavyBase border border-rcGold/30 text-rcGold hover:bg-rcGold hover:text-rcNavyBase py-3 rounded-2xl font-black uppercase tracking-widest text-[10px] transition-all">${t('common.continue')}</button>
          </div>
        `}
      </div>
    `;
  }

  // -------------------- ui state helpers --------------------
  window.setBuyAmount = function (v) {
    window.APP_STATE.ui.buyAmount = Number(v || 0);
  };

  window.setBuyNetwork = function (n) {
    window.APP_STATE.ui.buyNetwork = String(n || 'TRC20').toUpperCase();
    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  window.clearInvoice = function () {
    window.APP_STATE.ui.activeInvoiceId = null;
    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  window.createStandardInvoice = function () {
    const store = getStore();
    const userId = (window.APP_STATE.user || {}).id;
    if (!store || !userId) return;

    const cfg = store.loadConfig();
    const offer = computeOffer({ usdtAmount: window.APP_STATE.ui.buyAmount, cfg });

    const network = String(window.APP_STATE.ui.buyNetwork || 'TRC20').toUpperCase();
    const inv = store.createDepositInvoice({ userId, mode: 'standard', localAmountUSD: offer.usd, network });
    // patch address based on network for clarity (store also sets defaults)
    inv.address = inv.address || defaultAddressFor(network);
    window.APP_STATE.ui.activeInvoiceId = inv.id;
    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  // legacy compatibility (in case any old button still calls these)
  window.setBuyMode = function () { /* promos removed */ };
  window.setBuyCurrency = function () { /* promos removed */ };
  window.confirmPromoAndCreateInvoice = function () { alert('Promos are disabled.'); };

  window.simulateConfirmations = function () {
    const store = getStore();
    const invoiceId = window.APP_STATE.ui.activeInvoiceId;
    if (!store || !invoiceId) return;

    store.progressDeposit(invoiceId);

    const userId = (window.APP_STATE.user || {}).id;
    if (userId) {
      const u = store.getUserById(userId);
      if (u) window.APP_STATE.user.balance = u.balanceCrown;
    }

    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  window.postDepositNextStep = function () {
    const store = getStore();
    const userId = (window.APP_STATE.user || {}).id;
    const pending = window.APP_STATE.ui.pendingJoinTableId;

    if (pending && store && userId) {
      const table = store.getTableById(pending);
      if (table) {
        const idx = (table.seats || []).findIndex(s => !s || !s.userId);
        if (idx >= 0) {
          try {
            store.seatPlayer({ userId, tableId: pending, seatIndex: idx });
            window.APP_STATE.ui.activeTableId = pending;
            window.APP_STATE.ui.pendingJoinTableId = null;
            window.navigateTo('poker_table');
            return;
          } catch (_) {
            // ignore and go to lobby
          }
        }
      }
    }

    window.navigateTo('smart_lobby');
  };

  // -------------------- QUICK BUY MODAL (non-intrusive overlay) --------------------
  window.openCryptoCheckoutModal = function () {
    const r = role(window.APP_STATE || {});
    if (r === 'guest') {
      // Guests must register before they can purchase
      if (typeof window.navigateTo === 'function') window.navigateTo('auth_register');
      return;
    }
    window.APP_STATE.ui = window.APP_STATE.ui || {};
    window.APP_STATE.ui.quickBuyOpen = true;
    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  window.closeCryptoCheckoutModal = function () {
    window.APP_STATE.ui = window.APP_STATE.ui || {};
    window.APP_STATE.ui.quickBuyOpen = false;
    if (typeof window.forceRerender === 'function') window.forceRerender();
  };

  window.renderQuickBuyModal = function (stateObj) {
    const t = window.t || ((k)=>k);
    const r = role(stateObj);
    const store = getStore();
    const cfg = store.loadConfig();

    stateObj.ui = stateObj.ui || {};
    if (!Number.isFinite(Number(stateObj.ui.buyAmount))) stateObj.ui.buyAmount = 250;
    if (!stateObj.ui.buyNetwork) stateObj.ui.buyNetwork = 'TRC20';

    const offer = computeOffer({ usdtAmount: stateObj.ui.buyAmount, cfg, network: stateObj.ui.buyNetwork });
    const invoiceId = stateObj.ui.activeInvoiceId;
    const invoice = invoiceId ? (store.loadDeposits().find(x => x.id === invoiceId) || null) : null;

    return `
      <div class="fixed inset-0 bg-rcNavyBase/90 backdrop-blur-md z-[300] flex items-center justify-center p-4" onclick="window.closeCryptoCheckoutModal()">
        <div class="glass-panel w-full max-w-5xl border border-rcGold/25 rounded-3xl overflow-hidden" onclick="event.stopPropagation()">
          <div class="flex items-center justify-between p-5 border-b border-rcNavyBorder bg-black/20">
            <div>
              <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('floating.quickBuy')}</div>
              <div class="text-white font-black text-xl mt-1">${t('checkout.buyCrown')} · ${t('checkout.cryptoCheckout')}</div>
              <div class="text-rcSlateLight text-xs mt-1">1 CROWN = 1 USDT • ${t('checkout.network')}: ${(window.wrapLTR?window.wrapLTR('TRC20'):'TRC20')} / ${(window.wrapLTR?window.wrapLTR('ERC20'):'ERC20')} • ${t('checkout.networkFee')} ${t('checkout.netCredited')}</div>
            </div>
            <button onclick="window.closeCryptoCheckoutModal()" class="text-rcSlate hover:text-white text-2xl px-3">✕</button>
          </div>

          <div class="p-6 grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div class="lg:col-span-2">
              <div class="bg-rcNavyPanel border border-rcNavyBorder rounded-2xl p-6 shadow-inner">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div class="md:col-span-2">
                    <label class="text-[9px] text-rcSlate uppercase tracking-widest font-bold">${t('checkout.amountUSDT')}</label>
                    <input id="buy_amount" type="number" value="${escapeHtml(stateObj.ui.buyAmount)}" min="0" class="mt-2 w-full poker-input p-3 rounded-xl text-sm" oninput="window.setBuyAmount(this.value)">
                  </div>
                  <div>
                    <label class="text-[9px] text-rcSlate uppercase tracking-widest font-bold">${t('checkout.network')}</label>
                    <select onchange="window.setBuyNetwork(this.value)" class="mt-2 w-full bg-rcNavyBase border border-rcNavyBorder text-white p-3 rounded-xl text-sm">
                      ${['TRC20','ERC20'].map(n => `<option value="${n}" ${stateObj.ui.buyNetwork===n?'selected':''}>${n}</option>`).join('')}
                    </select>
                    <div class="mt-2 text-[11px] text-rcSlateLight">
                      ⚠️ ${t('checkout.networksWarning',{TRC20:(window.wrapLTR?window.wrapLTR('TRC20'):'TRC20'), ERC20:(window.wrapLTR?window.wrapLTR('ERC20'):'ERC20')})}
                    </div>
                  </div>
                </div>

                <div class="mt-6 bg-black/20 border border-rcNavyBorder rounded-2xl p-5">
                  <div class="text-rcGold text-[10px] font-black uppercase tracking-widest">${t('checkout.youReceive')}</div>
                  <div class="text-rcGold font-mono font-black text-3xl mt-2">${fmt(offer.crowns, 2)} CROWN</div>
                  <div class="mt-3 space-y-1 text-sm">
                    <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.gross')}</span><span class="text-white font-mono font-bold">${fmt(offer.usdt,2)} USDT</span></div>
                    <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.networkFee')}</span><span class="text-rcRed font-mono font-bold">-${fmt(offer.networkFee,2)} USDT</span></div>
                    <div class="flex items-center justify-between"><span class="text-rcSlateLight">${t('checkout.netCredited')}</span><span class="text-rcGold font-mono font-black">${fmt(offer.netUSDT,2)} USDT</span></div>
                  </div>
                </div>

                <div class="mt-5 flex gap-3">
                  <button onclick="window.createStandardInvoice()" class="flex-1 poker-chip-btn py-3 rounded-2xl text-rcNavyBase font-black uppercase tracking-widest text-[10px]">${t('checkout.createInvoice')}</button>
                  <button onclick="window.closeCryptoCheckoutModal()" class="px-5 py-3 rounded-2xl bg-rcNavyBase border border-rcNavyBorder text-rcSlateLight hover:text-white font-bold uppercase text-[10px] tracking-widest">${t('common.close')}</button>
                </div>
              </div>
            </div>

            <div>
              ${renderInvoicePanel(invoice, stateObj)}
            </div>
          </div>
        </div>
      </div>
    `;
  };

})();