/**
 * ROYAL GATEWAY - HEALTH / CRASH TEST
 *
 * What it checks:
 * - Can authenticate (via COOKIE_JAR/COOKIE or email+password)
 * - Can create invoices for ERC20 + TRC20
 * - Can fetch invoice status and validate shape
 * - Optional: run workers once in-process to catch crashes (RUN_WORKERS_ONCE=1)
 *
 * Run examples:
 *   DOTENV_PATH=.env.tests node scripts/gateway_health_crash_test.js
 *   RUN_WORKERS_ONCE=1 DOTENV_PATH=.env.tests node scripts/gateway_health_crash_test.js
 *
 * Auth options:
 * - Preferred: COOKIE_JAR=cookies.txt  (generated by curl login)
 * - Or: COOKIE="jwt=...."
 * - Or: TEST_EMAIL + TEST_PASSWORD (script will login)
 */

const dotenv = require('dotenv');
dotenv.config({ path: process.env.DOTENV_PATH || '.env' });

const fs = require('fs');
const axios = require('axios');

const API = process.env.TEST_API_BASE_URL || 'http://localhost:3000/api/v1';
const N_PER_NETWORK = Number(process.env.TEST_INVOICES_PER_NETWORK || 10);
const NETWORKS = (process.env.TEST_NETWORKS || 'ERC20,TRC20').split(',').map(s => s.trim());

function must(k) {
  const v = process.env[k];
  if (!v) throw new Error(`Missing env ${k}`);
  return v;
}

function cookieFromJar(jarPath) {
  if (!jarPath || !fs.existsSync(jarPath)) return null;
  const txt = fs.readFileSync(jarPath, 'utf8');
  const line = txt.split('\n').find(l => l.includes('\tjwt\t'));
  if (!line) return null;
  const parts = line.split('\t');
  const value = parts[parts.length - 1]?.trim();
  if (!value) return null;
  return `jwt=${value}`;
}

async function getCookieHeader() {
  if (process.env.COOKIE) return process.env.COOKIE.startsWith('jwt=') ? process.env.COOKIE : `jwt=${process.env.COOKIE}`;
  // Default to cookies.txt if not provided
  const jar = process.env.COOKIE_JAR || 'cookies.txt';
  if (fs.existsSync(jar)) {
    const c = cookieFromJar(jar);
    if (c) return c;
  }

  // fallback: login
  const email = must('TEST_EMAIL');
  const password = must('TEST_PASSWORD');
  const res = await axios.post(`${API}/auth/login`, { email, password }, { validateStatus: () => true });
  if (res.status !== 200) throw new Error(`Login failed: ${res.status} ${JSON.stringify(res.data)}`);
  const setCookie = res.headers['set-cookie'];
  if (!setCookie || !setCookie.length) throw new Error('No Set-Cookie returned');
  return setCookie[0].split(';')[0]; // jwt=...
}

async function createInvoice(cookie, network) {
  const res = await axios.post(`${API}/gateway/invoices`, { network }, {
    headers: { Cookie: cookie },
    validateStatus: () => true,
  });
  if (res.status !== 201) throw new Error(`Create invoice failed ${network}: ${res.status} ${JSON.stringify(res.data)}`);
  return res.data.data;
}

async function getStatus(cookie, invoiceId) {
  const res = await axios.get(`${API}/gateway/invoices/${invoiceId}/status`, {
    headers: { Cookie: cookie },
    validateStatus: () => true,
  });
  if (res.status !== 200) throw new Error(`Status failed: ${res.status} ${JSON.stringify(res.data)}`);
  return res.data.data;
}

function assertInvoiceShape(s) {
  const mustFields = ['invoiceId','network','depositAddress','status','requiredConfirmations','confirmations','expiresAt'];
  for (const f of mustFields) {
    if (s[f] === undefined || s[f] === null) throw new Error(`Missing field in status: ${f}`);
  }
  const allowed = new Set(['CREATED','WAITING','DETECTED','CONFIRMING','CONFIRMED','CREDITED','EXPIRED','FAILED','NEEDS_REVIEW','HOLD','DUST']);
  if (!allowed.has(s.status)) throw new Error(`Invalid status: ${s.status}`);
}

async function runWorkersOnceOptional() {
  if (String(process.env.RUN_WORKERS_ONCE || '') !== '1') return;

  // These requires work when the tests folder is inside Backend/scripts (../workers exists)
  const ethWorker = require('../workers/gatewayEthWorker');
  const tronWorker = require('../workers/gatewayTronWorker');
  const outbox = require('../workers/gatewayOutboxPublisher');

  await ethWorker.runOnce();
  await tronWorker.runOnce();
  await outbox.runOnce(200);
}

async function main() {
  const cookie = await getCookieHeader();
  const ids = [];

  for (const net of NETWORKS) {
    for (let i = 0; i < N_PER_NETWORK; i++) {
      const inv = await createInvoice(cookie, net);
      ids.push(inv.invoiceId);
    }
  }

  for (const id of ids) {
    const st = await getStatus(cookie, id);
    assertInvoiceShape(st);
  }

  await runWorkersOnceOptional();

  console.log('✅ HEALTH/CRASH TEST PASSED');
  process.exit(0);
}

main().catch((e) => {
  console.error('❌ HEALTH/CRASH TEST FAILED:', e.message);
  process.exit(1);
});
